# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6db7d40620d4c578fd0f95d7c6b69b1ad4cd25d77920b60689b21e51219d2e7abd8527d5ed2f914d95416f4c476160bcc36962702bc4cc7454b54bab97766199

test:
  secret_key_base: 3d8f812561929e4accb0b8e6b6988de7ef0a727a21e44f619fb2fdfdaf800d77d6820086cc7de8da80ed6065edb54265bf7776d74e2283b58865242dcac9f6e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
